# Generated by Django 5.1.1 on 2024-09-25 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('DEL', 'Deleted'), ('FRM', 'Formed'), ('COM', 'Completed'), ('REJ', 'Rejected')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('format', models.CharField(max_length=8)),
                ('size', models.IntegerField()),
                ('file_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filetransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('desc', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], max_length=1)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('uni', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileTransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('file_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filetransfer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipient')),
            ],
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='recipients',
            field=models.ManyToManyField(through='app.FileTransferRecipient', to='app.recipient'),
        ),
        migrations.AddConstraint(
            model_name='filetransferrecipient',
            constraint=models.UniqueConstraint(fields=('file_transfer', 'recipient', 'comment'), name='unique_transfer_recipient_comment'),
        ),
        migrations.AddConstraint(
            model_name='filetransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('sender',), name='unique_draft_per_sender'),
        ),
    ]
