# Generated by Django 5.1.1 on 2024-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filetransferrecipient',
            name='unique_transfer_recipient_comment',
        ),
        migrations.AddConstraint(
            model_name='filetransferrecipient',
            constraint=models.UniqueConstraint(fields=('file_transfer', 'recipient'), name='unique_transfer_recipient'),
        ),
    ]
