# Generated by Django 5.1.1 on 2024-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesendingprocess',
            name='recipients',
            field=models.ManyToManyField(through='app.FileSendingProcessRecipient', to='app.recipient'),
        ),
    ]
