# Generated by Django 5.1.1 on 2024-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filesendingprocess_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='uni',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
