# Generated by Django 5.1.1 on 2024-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipient_uni'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('format', models.CharField(max_length=8)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipient',
            name='desc',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='filesendingprocess',
            name='files',
            field=models.ManyToManyField(to='app.file'),
        ),
    ]
