# Generated by Django 5.1.1 on 2024-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file_alter_recipient_desc_filesendingprocess_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
